name: Build firmware

on:

  # On sketch change 
  push:
    paths:
      - "filesystem/version.txt"
      
  # On workflow dispatch
  workflow_dispatch:


jobs:

  # Compile code
  compile:

    runs-on: ubuntu-latest
    
    steps:

      # Clone repository
      - name: Clone repository
        uses: actions/checkout@main

      # Setup arduino CLI
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      # Configure platform
      - name: Configure platform
        run: |
          arduino-cli config init 
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
  
          arduino-cli lib install "ArduinoJson" "Adafruit NeoPixel" "ESPAsyncWebSrv"
          arduino-cli lib install --git-url "" || true

          # Compile
      - name: Compile sketch and pack filesystems
        run: |
          mkdir ./program/build || true
          /home/runner/.arduino15/packages/esp8266/tools/mkspiffs/**/mkspiffs -c ./filesystem/backup -b 8192 -p 256 -s 102400 -- ./program/build/backup-filesystem.bin
          /home/runner/.arduino15/packages/esp8266/tools/mkspiffs/**/mkspiffs -c ./filesystem/main -b 8192 -p 256 -s 524288 -- ./program/build/filesystem.bin
          arduino-cli compile -b "esp8266:esp8266:nodemcuv2" -e './program'
          
      # Upload to repository
      - name: Push changes to repo
        run: |
          mkdir ./updater || true
          cp ./program/build/**/*.ino.bin ./updater/firmware.bin
          cp ./program/build/backup-filesystem.bin ./updater/backup-filesystem.bin
          cp ./program/build/filesystem.bin ./updater/filesystem.bin
          cp ./filesystem/version.txt ./updater/build-version.txt
          rm -rf ./program/build
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git pull
          git add .
          git commit -m "🏗️ Firmware v$(grep 'Firmware:' ./updater/build-version.txt | cut -d' ' -f2) | FS v$(grep 'Filesystem:' ./updater/build-version.txt | cut -d' ' -f2)"
          git push