name: Build firmware
on: [push, workflow_dispatch]

jobs:

  # Compile code
  compile:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Compile firmware & Build filesystem
        run: |          
          pio run
          pio run --target buildfs

          cp ./data/version.txt ./updater/build-version.txt
          cp .pio/build/*/firmware.bin ./updater/firmware.bin
          cp .pio/build/*/littlefs.bin ./updater/filesystem.bin
          
      - name: (?) Push files
        run: |

          if [ -n "$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} -- 'data/version.txt')" ]; then
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            git add .
            git commit -m "🏗️ Firmware v$(grep 'Firmware:' ./updater/build-version.txt | cut -d' ' -f2) | FS v$(grep 'Filesystem:' ./updater/build-version.txt | cut -d' ' -f2)"
            git push
          else
            echo "Version list not changed, aborting push."
          fi